Add 'npm rebuild' following the error message in travis
Q: is glibc on travis to old to build this, or do we have the wrong version of grpc?

From https://travis-ci.org/mostalive/purescript-firebase
Error: Failed to load gRPC binary module because it was not installed for the current system

Expected directory: node-v72-linux-x64-glibc

Found: [node-v67-linux-x64-glibc]

This problem can often be fixed by running "npm rebuild" on the current system

Original error: Cannot find module '/home/travis/build/mostalive/purescript-firebase/node_modules/@firebase/firestore/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node'

Require stack:

- /home/travis/build/mostalive/purescript-firebase/node_modules/@firebase/firestore/node_modules/grpc/src/grpc_extension.js

- /home/travis/build/mostalive/purescript-firebase/node_modules/@firebase/firestore/node_modules/grpc/src/client_interceptors.js

- /home/travis/build/mostalive/purescript-firebase/node_modules/@firebase/firestore/node_modules/grpc/src/client.js

- /home/travis/build/mostalive/purescript-firebase/node_modules/@firebase/firestore/node_modules/grpc/index.js

- /home/travis/build/mostalive/purescript-firebase/node_modules/@firebase/firestore/dist/index.node.cjs.js

- /home/travis/build/mostalive/purescript-firebase/node_modules/@firebase/testing/node_modules/firebase/dist/index.node.cjs.js

- /home/travis/build/mostalive/purescript-firebase/node_modules/@firebase/testing/dist/index.cjs.js

- /home/travis

/build/mostalive/purescript-firebase/output/Web.Firebase.Testing/foreign.js